### ISSUE TITLE
[TODO] Add more information to ScenarioDescription

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/scenarionet#27]
- [x] Use exterior instead of boundary to extract the boundary.
- Connectivity (Check if the way we store connectivity is good or not.)
  - [x] nuPlan
  - [x] nuScenes
  - [x] PG
- RoadBlock/crosswalks/sidewalks
  - [x] nuPlan
  - [x] nuScenes
  - [x] PG
 
- [x] Sanity-check map structure. Use `.get` to get `IS_CONNECTOR`.
- [x] Update ALL test scenarios in asset folder.
